apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: production-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /v2
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
      - mywebsite.com
    secretName: mywebsite-tls-updated
  rules:
  - host: mywebsite.com
    http:
      paths:
      - path: /api/v2
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80