apiVersion: v1
kind: Pod
metadata:
  name: failing-readiness-pod
spec:
  containers:
  - name: my-container
    image: busybox
    command: ["sh", "-c", "while true; do echo 'Running...'; sleep 5; done"]
    readinessProbe:
      exec:
        command:
        - sh
        - -c
        - "exit 1"                                    
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3